### ISSUE TITLE
Development dead?

### ISSUE THREAD

**Issue by axel-1267** [techyminati/releases#1]
Hi,
Fantastic rom!
Are you still working on this project for Redmi GO?
Contact me if you need testing.

**Comment by techyminati** [comment]
My tiare died and we've no testers.

**Comment by axel-1267** [comment]
Today i've also flashed CipherOS on mine. Very good project.
I have no Android coding experience, but i think i can contribute to this my own way.
If i send you a good condition Redmi Go (Tiare), free of charge of course, could this help development?

**Comment by techyminati** [comment]
Hi, will you be available to test ROMs? I don't really want to you ship devices all the way from your place to my place free-of-cost. 

Do you have telegram account?

**Comment by axel-1267** [comment]
Yes, i will send you a pm to your Gmail tomorrow after work.

**Comment by techyminati** [comment]
okay, I didnt recieve any email
